spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zee5appprod
    username: root
    password: Pass@123
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.zee.zee5app.utils.CustomTableNameStrategy
    show-sql: true
   